trigger:
- master
- main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- bash: cmake $(System.DefaultWorkingDirectory) -DBUILD_VCPKG=ON
  displayName: Configure CMake
  env:
    CXX: ${{ cxx }}
  workingDirectory: $(System.DefaultWorkingDirectory)

- bash: cmake --build . --config $BUILD_TYPE --target install
  displayName: Build & Install
  workingDirectory: $(System.DefaultWorkingDirectory)

- bash: ctest -C $BUILD_TYPE --output-on-failure
  displayName: Test
  workingDirectory: $(System.DefaultWorkingDirectory)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/artifacts'
    includeRootFolder: false

- task: GithubRelease@1 
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: CihanSari
    repositoryName: CihanSari/binary_bakery
    tagSource: auto
    tag: $(Build.BuildNumber)