trigger:
- master
- main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- script: cmake $(Build.Repository.LocalPath) -DBUILD_VCPKG=ON
  displayName: Configure CMake

- script: cmake --build . --config $BUILD_TYPE --target install
  displayName: Build & Install

- script: ctest -C $BUILD_TYPE --output-on-failure
  displayName: Test

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)/artifacts'
    includeRootFolder: false

# - task: GithubRelease@1 
#   displayName: 'Create GitHub Release'      
#   inputs:
#     gitHubConnection: CihanSari
#     repositoryName: CihanSari/binary_bakery
#     tagSource: auto
#     tag: $(Build.BuildNumber)