trigger:
- master
- main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      cxx: g++-11
    windows:
      imageName: 'windows-latest'
      cxx: msvc

pool:
  vmImage: $(imageName)

steps:
- script: |
    sudo apt update
    sudo apt -y install gcc-11 g++-11
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
  displayName: Install gcc-11


- script: cmake $(Build.Repository.LocalPath) -DBUILD_VCPKG=ON
  displayName: Configure CMake
  env:
    CXX: $(cxx)

- script: cmake --build . --config Release --target install
  displayName: Build & Install

- script: ctest -C Release --output-on-failure
  displayName: Test

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)/artifacts'
    includeRootFolder: false

# - task: GithubRelease@1 
#   displayName: 'Create GitHub Release'      
#   inputs:
#     gitHubConnection: CihanSari
#     repositoryName: CihanSari/binary_bakery
#     tagSource: auto
#     tag: $(Build.BuildNumber)