trigger:
- master
- main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- bash:
  displayName: Configure CMake
  env:
    CXX: ${{ cxx }}
  workingDirectory: $(System.DefaultWorkingDirectory)
  script: cmake $(System.DefaultWorkingDirectory) -DBUILD_VCPKG=ON

- bash:
  displayName: Build & Install
  workingDirectory: $(System.DefaultWorkingDirectory)
  script: cmake --build . --config $BUILD_TYPE --target install

- bash:
  displayName: Test
  workingDirectory: $(System.DefaultWorkingDirectory)
  # Use CTest to run tests
  script: ctest -C $BUILD_TYPE --output-on-failure

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/artifacts'
    includeRootFolder: false

- task: GithubRelease@1 
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: CihanSari
    repositoryName: CihanSari/binary_bakery
    tagSource: auto
    tag: $(Build.BuildNumber)