# Output path of the resulting header. Relative to the path of first parameter
# if not an absolute path.
output_filename = "binary_bakery_payload.h"

# Maximum number of rows in output header
max_columns = 100

# Smart means that images will be detected as such and treated differently. In
# particular that means their bitmap content will be encoded instead of the
# raw file content. Also, dimensions and bpp will be available in the header.
# true: Images will be treated differently [default]
# false: Images will be encoded like all binary files
smart_mode = true

# Any of: ["none", "zstd", "lz4"]
# "none": no compression
# "zstd": Zstandard, see https://github.com/facebook/zstd
# "LZ4": see https://github.com/lz4/lz4
compression_mode = "none"

# True: Encoder waits for a key press at the end, allowing you to read some size information
# False: Ends program immediately
prompt_for_key = true

# Store image pixel information from bottom row to top or the other way?
# "bottom_to_top": First pixel is bottom left
# "top_to_bottom": First pixel is top left
image_loading_direction = "bottom_to_top"
